# Generated by Django 3.1.5 on 2021-03-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummyuser',
            old_name='name',
            new_name='username',
        ),
    ]
