# Generated by Django 3.1.5 on 2021-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_auto_20210319_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyuser',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
