# Generated by Django 3.1.5 on 2021-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saturn', '0002_delete_dummyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
            ],
        ),
    ]
